version: "3"

services:
  demoapp:
    build: ./demoapp
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - CLOUD_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  modsecurity:
    image: owasp/modsecurity-crs:3-nginx-202301110601
    environment:
      BACKEND: http://demoapp:8080
      PORT: "80"
      METRICS_ALLOW_FROM: all
    ports:
      - 8081:80

  attacker:
    build: ./attacker
    ports:
      - 8082:80
